### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by marbocub** [Fraxinus-3D/docs#2]
次の2ページのH2要素がすべてFraxinuになってます
enclosure.md
enclosure.en.md

**Comment by Tiryoh** [comment]
ご指摘ありがとうございます！修正します

**Comment by Tiryoh** [comment]
こちらで修正しました。ご指摘ありがとうございました！

https://github.com/Fraxinus-3D/docs/commit/e0c50d987eebe3eaabf2bf92d7b5a0f0cb5c4eab
